server:
  port: 8080
  servlet:
    context-path: /jshERP-boot
    session:
      timeout: 36000
  tomcat:
    basedir: /opt/tmp/tomcat

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mysql://${DB_IP:172.17.0.3}:${DB_PORT:3306}/${DB_NAME:jsh_erp}?autoReconnect=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    type: com.zaxxer.hikari.HikariDataSource
#    schema: classpath:schema.sql
#    initialization-mode: never
    #    initialization-mode: always
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000 # 空闲超时时间设为10分钟
      pool-name: HikariCP
      max-lifetime: 28000000 # 连接最大生命周期设为7小时46分钟
      connection-timeout: 60000
      connection-test-query: SELECT 1
      leak-detection-threshold: 2000 # 连接泄漏检测阈值设为2秒
  redis:
    host: ${REDIS_HOST:172.17.0.2}
    port: 6379
    password: jHWVClW8d05uqYc
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760

mybatis-plus:
  mapper-locations: classpath:./mapper_xml/*.xml

manage:
  roleId: 10

tenant:
  userNumLimit: 1000000
  tryDayLimit: 3000

plugin:
  runMode: prod
  pluginPath: plugins
  pluginConfigFilePath: pluginConfig

file:
  uploadType: 1
  path: /opt/jshERP/upload
