package com.jsh.erp.datasource.entities;

public class Functions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.PNumber
     *
     * @mbggenerated
     */
    private String pnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.State
     *
     * @mbggenerated
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.PushBtn
     *
     * @mbggenerated
     */
    private String pushbtn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_functions.delete_Flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Id
     *
     * @return the value of jsh_functions.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Id
     *
     * @param id the value for jsh_functions.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Number
     *
     * @return the value of jsh_functions.Number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Number
     *
     * @param number the value for jsh_functions.Number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Name
     *
     * @return the value of jsh_functions.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Name
     *
     * @param name the value for jsh_functions.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.PNumber
     *
     * @return the value of jsh_functions.PNumber
     *
     * @mbggenerated
     */
    public String getPnumber() {
        return pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.PNumber
     *
     * @param pnumber the value for jsh_functions.PNumber
     *
     * @mbggenerated
     */
    public void setPnumber(String pnumber) {
        this.pnumber = pnumber == null ? null : pnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.URL
     *
     * @return the value of jsh_functions.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.URL
     *
     * @param url the value for jsh_functions.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.State
     *
     * @return the value of jsh_functions.State
     *
     * @mbggenerated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.State
     *
     * @param state the value for jsh_functions.State
     *
     * @mbggenerated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Sort
     *
     * @return the value of jsh_functions.Sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Sort
     *
     * @param sort the value for jsh_functions.Sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Enabled
     *
     * @return the value of jsh_functions.Enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Enabled
     *
     * @param enabled the value for jsh_functions.Enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.Type
     *
     * @return the value of jsh_functions.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.Type
     *
     * @param type the value for jsh_functions.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.PushBtn
     *
     * @return the value of jsh_functions.PushBtn
     *
     * @mbggenerated
     */
    public String getPushbtn() {
        return pushbtn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.PushBtn
     *
     * @param pushbtn the value for jsh_functions.PushBtn
     *
     * @mbggenerated
     */
    public void setPushbtn(String pushbtn) {
        this.pushbtn = pushbtn == null ? null : pushbtn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.icon
     *
     * @return the value of jsh_functions.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.icon
     *
     * @param icon the value for jsh_functions.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_functions.delete_Flag
     *
     * @return the value of jsh_functions.delete_Flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_functions.delete_Flag
     *
     * @param deleteFlag the value for jsh_functions.delete_Flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}