package com.jsh.erp.datasource.entities;

public class MaterialCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.CategoryLevel
     *
     * @mbggenerated
     */
    private Short categorylevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_materialcategory.ParentId
     *
     * @mbggenerated
     */
    private Long parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.Id
     *
     * @return the value of jsh_materialcategory.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.Id
     *
     * @param id the value for jsh_materialcategory.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.Name
     *
     * @return the value of jsh_materialcategory.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.Name
     *
     * @param name the value for jsh_materialcategory.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.CategoryLevel
     *
     * @return the value of jsh_materialcategory.CategoryLevel
     *
     * @mbggenerated
     */
    public Short getCategorylevel() {
        return categorylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.CategoryLevel
     *
     * @param categorylevel the value for jsh_materialcategory.CategoryLevel
     *
     * @mbggenerated
     */
    public void setCategorylevel(Short categorylevel) {
        this.categorylevel = categorylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_materialcategory.ParentId
     *
     * @return the value of jsh_materialcategory.ParentId
     *
     * @mbggenerated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_materialcategory.ParentId
     *
     * @param parentid the value for jsh_materialcategory.ParentId
     *
     * @mbggenerated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }
}