package com.jsh.erp.datasource.entities;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.supplier
     *
     * @mbggenerated
     */
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.contacts
     *
     * @mbggenerated
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.phonenum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.isystem
     *
     * @mbggenerated
     */
    private Byte isystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.AdvanceIn
     *
     * @mbggenerated
     */
    private Double advancein;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.BeginNeedGet
     *
     * @mbggenerated
     */
    private Double beginneedget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.BeginNeedPay
     *
     * @mbggenerated
     */
    private Double beginneedpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.AllNeedGet
     *
     * @mbggenerated
     */
    private Double allneedget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.AllNeedPay
     *
     * @mbggenerated
     */
    private Double allneedpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.taxNum
     *
     * @mbggenerated
     */
    private String taxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.bankName
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.accountNumber
     *
     * @mbggenerated
     */
    private String accountnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_supplier.taxRate
     *
     * @mbggenerated
     */
    private Double taxrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.id
     *
     * @return the value of jsh_supplier.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.id
     *
     * @param id the value for jsh_supplier.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.supplier
     *
     * @return the value of jsh_supplier.supplier
     *
     * @mbggenerated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.supplier
     *
     * @param supplier the value for jsh_supplier.supplier
     *
     * @mbggenerated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.contacts
     *
     * @return the value of jsh_supplier.contacts
     *
     * @mbggenerated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.contacts
     *
     * @param contacts the value for jsh_supplier.contacts
     *
     * @mbggenerated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.phonenum
     *
     * @return the value of jsh_supplier.phonenum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.phonenum
     *
     * @param phonenum the value for jsh_supplier.phonenum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.email
     *
     * @return the value of jsh_supplier.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.email
     *
     * @param email the value for jsh_supplier.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.description
     *
     * @return the value of jsh_supplier.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.description
     *
     * @param description the value for jsh_supplier.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.isystem
     *
     * @return the value of jsh_supplier.isystem
     *
     * @mbggenerated
     */
    public Byte getIsystem() {
        return isystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.isystem
     *
     * @param isystem the value for jsh_supplier.isystem
     *
     * @mbggenerated
     */
    public void setIsystem(Byte isystem) {
        this.isystem = isystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.type
     *
     * @return the value of jsh_supplier.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.type
     *
     * @param type the value for jsh_supplier.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.enabled
     *
     * @return the value of jsh_supplier.enabled
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.enabled
     *
     * @param enabled the value for jsh_supplier.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.AdvanceIn
     *
     * @return the value of jsh_supplier.AdvanceIn
     *
     * @mbggenerated
     */
    public Double getAdvancein() {
        return advancein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.AdvanceIn
     *
     * @param advancein the value for jsh_supplier.AdvanceIn
     *
     * @mbggenerated
     */
    public void setAdvancein(Double advancein) {
        this.advancein = advancein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.BeginNeedGet
     *
     * @return the value of jsh_supplier.BeginNeedGet
     *
     * @mbggenerated
     */
    public Double getBeginneedget() {
        return beginneedget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.BeginNeedGet
     *
     * @param beginneedget the value for jsh_supplier.BeginNeedGet
     *
     * @mbggenerated
     */
    public void setBeginneedget(Double beginneedget) {
        this.beginneedget = beginneedget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.BeginNeedPay
     *
     * @return the value of jsh_supplier.BeginNeedPay
     *
     * @mbggenerated
     */
    public Double getBeginneedpay() {
        return beginneedpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.BeginNeedPay
     *
     * @param beginneedpay the value for jsh_supplier.BeginNeedPay
     *
     * @mbggenerated
     */
    public void setBeginneedpay(Double beginneedpay) {
        this.beginneedpay = beginneedpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.AllNeedGet
     *
     * @return the value of jsh_supplier.AllNeedGet
     *
     * @mbggenerated
     */
    public Double getAllneedget() {
        return allneedget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.AllNeedGet
     *
     * @param allneedget the value for jsh_supplier.AllNeedGet
     *
     * @mbggenerated
     */
    public void setAllneedget(Double allneedget) {
        this.allneedget = allneedget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.AllNeedPay
     *
     * @return the value of jsh_supplier.AllNeedPay
     *
     * @mbggenerated
     */
    public Double getAllneedpay() {
        return allneedpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.AllNeedPay
     *
     * @param allneedpay the value for jsh_supplier.AllNeedPay
     *
     * @mbggenerated
     */
    public void setAllneedpay(Double allneedpay) {
        this.allneedpay = allneedpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.fax
     *
     * @return the value of jsh_supplier.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.fax
     *
     * @param fax the value for jsh_supplier.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.telephone
     *
     * @return the value of jsh_supplier.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.telephone
     *
     * @param telephone the value for jsh_supplier.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.address
     *
     * @return the value of jsh_supplier.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.address
     *
     * @param address the value for jsh_supplier.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.taxNum
     *
     * @return the value of jsh_supplier.taxNum
     *
     * @mbggenerated
     */
    public String getTaxnum() {
        return taxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.taxNum
     *
     * @param taxnum the value for jsh_supplier.taxNum
     *
     * @mbggenerated
     */
    public void setTaxnum(String taxnum) {
        this.taxnum = taxnum == null ? null : taxnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.bankName
     *
     * @return the value of jsh_supplier.bankName
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.bankName
     *
     * @param bankname the value for jsh_supplier.bankName
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.accountNumber
     *
     * @return the value of jsh_supplier.accountNumber
     *
     * @mbggenerated
     */
    public String getAccountnumber() {
        return accountnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.accountNumber
     *
     * @param accountnumber the value for jsh_supplier.accountNumber
     *
     * @mbggenerated
     */
    public void setAccountnumber(String accountnumber) {
        this.accountnumber = accountnumber == null ? null : accountnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_supplier.taxRate
     *
     * @return the value of jsh_supplier.taxRate
     *
     * @mbggenerated
     */
    public Double getTaxrate() {
        return taxrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_supplier.taxRate
     *
     * @param taxrate the value for jsh_supplier.taxRate
     *
     * @mbggenerated
     */
    public void setTaxrate(Double taxrate) {
        this.taxrate = taxrate;
    }
}