package com.jsh.erp.datasource.entities;

public class SystemConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_contacts
     *
     * @mbggenerated
     */
    private String companyContacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_address
     *
     * @mbggenerated
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_tel
     *
     * @mbggenerated
     */
    private String companyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_fax
     *
     * @mbggenerated
     */
    private String companyFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.company_post_code
     *
     * @mbggenerated
     */
    private String companyPostCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.depot_flag
     *
     * @mbggenerated
     */
    private String depotFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.customer_flag
     *
     * @mbggenerated
     */
    private String customerFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.tenant_id
     *
     * @mbggenerated
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_systemconfig.delete_Flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.id
     *
     * @return the value of jsh_systemconfig.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.id
     *
     * @param id the value for jsh_systemconfig.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_name
     *
     * @return the value of jsh_systemconfig.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_name
     *
     * @param companyName the value for jsh_systemconfig.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_contacts
     *
     * @return the value of jsh_systemconfig.company_contacts
     *
     * @mbggenerated
     */
    public String getCompanyContacts() {
        return companyContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_contacts
     *
     * @param companyContacts the value for jsh_systemconfig.company_contacts
     *
     * @mbggenerated
     */
    public void setCompanyContacts(String companyContacts) {
        this.companyContacts = companyContacts == null ? null : companyContacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_address
     *
     * @return the value of jsh_systemconfig.company_address
     *
     * @mbggenerated
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_address
     *
     * @param companyAddress the value for jsh_systemconfig.company_address
     *
     * @mbggenerated
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_tel
     *
     * @return the value of jsh_systemconfig.company_tel
     *
     * @mbggenerated
     */
    public String getCompanyTel() {
        return companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_tel
     *
     * @param companyTel the value for jsh_systemconfig.company_tel
     *
     * @mbggenerated
     */
    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel == null ? null : companyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_fax
     *
     * @return the value of jsh_systemconfig.company_fax
     *
     * @mbggenerated
     */
    public String getCompanyFax() {
        return companyFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_fax
     *
     * @param companyFax the value for jsh_systemconfig.company_fax
     *
     * @mbggenerated
     */
    public void setCompanyFax(String companyFax) {
        this.companyFax = companyFax == null ? null : companyFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.company_post_code
     *
     * @return the value of jsh_systemconfig.company_post_code
     *
     * @mbggenerated
     */
    public String getCompanyPostCode() {
        return companyPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.company_post_code
     *
     * @param companyPostCode the value for jsh_systemconfig.company_post_code
     *
     * @mbggenerated
     */
    public void setCompanyPostCode(String companyPostCode) {
        this.companyPostCode = companyPostCode == null ? null : companyPostCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.depot_flag
     *
     * @return the value of jsh_systemconfig.depot_flag
     *
     * @mbggenerated
     */
    public String getDepotFlag() {
        return depotFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.depot_flag
     *
     * @param depotFlag the value for jsh_systemconfig.depot_flag
     *
     * @mbggenerated
     */
    public void setDepotFlag(String depotFlag) {
        this.depotFlag = depotFlag == null ? null : depotFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.customer_flag
     *
     * @return the value of jsh_systemconfig.customer_flag
     *
     * @mbggenerated
     */
    public String getCustomerFlag() {
        return customerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.customer_flag
     *
     * @param customerFlag the value for jsh_systemconfig.customer_flag
     *
     * @mbggenerated
     */
    public void setCustomerFlag(String customerFlag) {
        this.customerFlag = customerFlag == null ? null : customerFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.tenant_id
     *
     * @return the value of jsh_systemconfig.tenant_id
     *
     * @mbggenerated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.tenant_id
     *
     * @param tenantId the value for jsh_systemconfig.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jsh_systemconfig.delete_Flag
     *
     * @return the value of jsh_systemconfig.delete_Flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jsh_systemconfig.delete_Flag
     *
     * @param deleteFlag the value for jsh_systemconfig.delete_Flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}