package com.jsh.erp.datasource.mappers;

import com.jsh.erp.datasource.entities.AssetCategory;
import com.jsh.erp.datasource.entities.AssetCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    int countByExample(AssetCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    int deleteByExample(AssetCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    int insert(AssetCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    int insertSelective(AssetCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    List<AssetCategory> selectByExample(AssetCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    AssetCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssetCategory record, @Param("example") AssetCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssetCategory record, @Param("example") AssetCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssetCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetcategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssetCategory record);
}