package com.jsh.erp.datasource.mappers;

import com.jsh.erp.datasource.entities.AssetName;
import com.jsh.erp.datasource.entities.AssetNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int countByExample(AssetNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int deleteByExample(AssetNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int insert(AssetName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int insertSelective(AssetName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    List<AssetName> selectByExampleWithBLOBs(AssetNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    List<AssetName> selectByExample(AssetNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    AssetName selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssetName record, @Param("example") AssetNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") AssetName record, @Param("example") AssetNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssetName record, @Param("example") AssetNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssetName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(AssetName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jsh_assetname
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssetName record);
}